"""tambah length nama_libur

Revision ID: 082631975b9d
Revises: 36f955a3bd4b
Create Date: 2026-08-18 09:49:38.007496
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '082631975b9d'
down_revision: Union[str, None] = '36f955a3bd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holidays', 'nama_libur',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holidays', 'nama_libur',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)
    # ### end Alembic commands ###
