"""add_log_reassignment_approval_table

Revision ID: 1b6f9e5e2601
Revises: 1cb6e5056c45
Create Date: 2026-09-10 17:52:36.173431
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b6f9e5e2601'
down_revision: Union[str, None] = '1cb6e5056c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_reassignment_approval',
    sa.Column('id_reassignment', sa.Integer(), nullable=False),
    sa.Column('id_log_cuti', sa.Integer(), nullable=True),
    sa.Column('id_pengajuan_kerja', sa.Integer(), nullable=True),
    sa.Column('id_pm_lama', sa.Integer(), nullable=False),
    sa.Column('id_pm_baru', sa.Integer(), nullable=True),
    sa.Column('alasan', sa.Text(), nullable=False),
    sa.Column('waktu_perubahan', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_log_cuti'], ['log_cuti.id_log_cuti'], ),
    sa.ForeignKeyConstraint(['id_pengajuan_kerja'], ['log_penambahan_kerja.id_pengajuan_kerja'], ),
    sa.ForeignKeyConstraint(['id_pm_baru'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_pm_lama'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_reassignment')
    )
    op.create_index(op.f('ix_log_reassignment_approval_id_reassignment'), 'log_reassignment_approval', ['id_reassignment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_reassignment_approval_id_reassignment'), table_name='log_reassignment_approval')
    op.drop_table('log_reassignment_approval')
    # ### end Alembic commands ###
