"""add_staff_hr_role

Revision ID: 1cb6e5056c45
Revises: 6c5da0c37047
Create Date: 2026-09-10 15:09:12.797789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '1cb6e5056c45'
down_revision: Union[str, None] = '6c5da0c37047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('karyawan', 'pm', 'hr', 'direktur'),
               type_=sa.Enum('karyawan', 'pm', 'hr', 'direktur', 'staff_hr'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('karyawan', 'pm', 'hr', 'direktur', 'staff_hr'),
               type_=mysql.ENUM('karyawan', 'pm', 'hr', 'direktur'),
               existing_nullable=False)
    # ### end Alembic commands ###
