"""add log_penambahan_kerja table

Revision ID: 2b6a4322d081
Revises: 9ff93a38d6a2
Create Date: 2026-08-24 13:31:46.042240
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b6a4322d081'
down_revision: Union[str, None] = '9ff93a38d6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_penambahan_kerja',
    sa.Column('id_pengajuan_kerja', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('keterangan_pengajuan', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('menunggu_pm', 'disetujui_pm', 'ditolak_pm'), nullable=False),
    sa.Column('diproses_pm', sa.Integer(), nullable=True),
    sa.Column('processed_at_pm', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['diproses_pm'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_pengajuan_kerja')
    )
    op.create_index(op.f('ix_log_penambahan_kerja_id_pengajuan_kerja'), 'log_penambahan_kerja', ['id_pengajuan_kerja'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_penambahan_kerja_id_pengajuan_kerja'), table_name='log_penambahan_kerja')
    op.drop_table('log_penambahan_kerja')
    # ### end Alembic commands ###
