"""make_id_pm_lama_nullable_log_reassignment

Revision ID: 369df610cbe9
Revises: 1b6f9e5e2601
Create Date: 2026-09-10 18:48:46.743474
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '369df610cbe9'
down_revision: Union[str, None] = '1b6f9e5e2601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_reassignment_approval', 'id_pm_lama',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_reassignment_approval', 'id_pm_lama',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
