"""tambah tabel holidays

Revision ID: 36f955a3bd4b
Revises: 6b41ec7fa4aa
Create Date: 2026-08-18 09:32:49.343444
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '36f955a3bd4b'
down_revision: Union[str, None] = '6b41ec7fa4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id_holiday', sa.Integer(), nullable=False),
    sa.Column('nama_libur', sa.String(length=35), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('is_cuti_bersama', sa.Boolean(), nullable=True),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_holiday')
    )
    op.create_index(op.f('ix_holidays_id_holiday'), 'holidays', ['id_holiday'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holidays_id_holiday'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
