"""tambah kolom status di users

Revision ID: 48fa8bea1e74
Revises: 082631975b9d
Create Date: 2026-08-19 15:14:46.645561
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48fa8bea1e74'
down_revision: Union[str, None] = '082631975b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('Aktif', 'Cuti'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
