"""init tables

Revision ID: 5704d1733b38
Revises: 
Create Date: 2026-08-13 10:05:48.842843
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5704d1733b38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departemen',
    sa.Column('id_departemen', sa.Integer(), nullable=False),
    sa.Column('nama_departemen', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id_departemen')
    )
    op.create_index(op.f('ix_departemen_id_departemen'), 'departemen', ['id_departemen'], unique=False)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('karyawan', 'pm', 'hr', 'direktur'), nullable=False),
    sa.Column('id_departemen', sa.Integer(), nullable=False),
    sa.Column('id_pm', sa.Integer(), nullable=True),
    sa.Column('total_cuti', sa.Integer(), nullable=True),
    sa.Column('sisa_cuti', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_departemen'], ['departemen.id_departemen'], ),
    sa.ForeignKeyConstraint(['id_pm'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('log_cuti',
    sa.Column('id_log_cuti', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('jenis_cuti', sa.String(length=30), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('keterangan_cuti', sa.Text(), nullable=False),
    sa.Column('pengganti', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('menunggu_pm', 'disetujui_pm', 'ditolak_pm', 'menunggu_hr', 'disetujui_hr', 'ditolak_hr', 'menunggu_direktur', 'disetujui_direktur', 'ditolak_direktur'), nullable=False),
    sa.Column('alasan_penolakan', sa.Text(), nullable=True),
    sa.Column('disetujui_pm', sa.Integer(), nullable=True),
    sa.Column('disetujui_hr', sa.Integer(), nullable=True),
    sa.Column('disetujui_direktur', sa.Integer(), nullable=True),
    sa.Column('approved_at_pm', sa.Date(), nullable=True),
    sa.Column('approved_at_hr', sa.Date(), nullable=True),
    sa.Column('approved_at_direktur', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['disetujui_direktur'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['disetujui_hr'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['disetujui_pm'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['pengganti'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_log_cuti')
    )
    op.create_index(op.f('ix_log_cuti_id_log_cuti'), 'log_cuti', ['id_log_cuti'], unique=False)
    op.create_table('log_cuti_ekstra',
    sa.Column('id_log_cuti_ekstra', sa.Integer(), nullable=False),
    sa.Column('id_penambah', sa.Integer(), nullable=False),
    sa.Column('jumlah_hari', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.Column('added_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_penambah'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_log_cuti_ekstra')
    )
    op.create_index(op.f('ix_log_cuti_ekstra_id_log_cuti_ekstra'), 'log_cuti_ekstra', ['id_log_cuti_ekstra'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_cuti_ekstra_id_log_cuti_ekstra'), table_name='log_cuti_ekstra')
    op.drop_table('log_cuti_ekstra')
    op.drop_index(op.f('ix_log_cuti_id_log_cuti'), table_name='log_cuti')
    op.drop_table('log_cuti')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departemen_id_departemen'), table_name='departemen')
    op.drop_table('departemen')
    # ### end Alembic commands ###
