"""add edited_at to log_cuti

Revision ID: 7a34d37bb74e
Revises: c3d4e5f6a7b8
Create Date: 2026-09-05 14:24:45.136189
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a34d37bb74e'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_cuti', sa.Column('edited_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_cuti', 'edited_at')
    # ### end Alembic commands ###
