"""tambah kolom tanggal pengjuan di log_cuti

Revision ID: a022dd4aeaaf
Revises: bcf0bd3db19f
Create Date: 2026-08-14 10:08:28.490840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a022dd4aeaaf'
down_revision: Union[str, None] = 'bcf0bd3db19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_cuti', sa.Column('tanggal_pengajuan', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_cuti', 'tanggal_pengajuan')
    # ### end Alembic commands ###
