"""add email no_telp tanggal_bergabung to users

Revision ID: a0ab8651db27
Revises: a022dd4aeaaf
Create Date: 2026-08-14 14:39:03.777349
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0ab8651db27'
down_revision: Union[str, None] = 'a022dd4aeaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('no_telp', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('tanggal_bergabung', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tanggal_bergabung')
    op.drop_column('users', 'no_telp')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
