"""add kolom username on users

Revision ID: bcf0bd3db19f
Revises: 5704d1733b38
Create Date: 2026-08-13 10:25:25.513460
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bcf0bd3db19f'
down_revision: Union[str, None] = '5704d1733b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
