"""tambah kolom sudah_dikurangi di holidays

Revision ID: f1a2b3c4d5e6
Revises: 082631975b9d
Create Date: 2026-08-23 10:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = '082631975b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('sudah_dikurangi', sa.Boolean(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holidays', 'sudah_dikurangi')
    # ### end Alembic commands ###

###
