"""add diproses_hr and keterangan_disetujui_hr to log_penambahan_kerja, add menunggu_direktur status

Revision ID: fdf3abe4ca8b
Revises: a1b2c3d4e5f6
Create Date: 2026-09-11 20:19:06.296233
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'fdf3abe4ca8b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_penambahan_kerja', sa.Column('diproses_hr', sa.Integer(), nullable=True))
    op.add_column('log_penambahan_kerja', sa.Column('keterangan_disetujui_hr', sa.Text(), nullable=True))
    op.alter_column('log_penambahan_kerja', 'status',
               existing_type=mysql.ENUM('menunggu_pm', 'disetujui_pm', 'ditolak_pm', 'menunggu_hr', 'disetujui_hr', 'ditolak_hr'),
               type_=sa.Enum('menunggu_pm', 'disetujui_pm', 'ditolak_pm', 'menunggu_hr', 'disetujui_hr', 'ditolak_hr', 'menunggu_direktur'),
               existing_nullable=False)
    op.create_foreign_key(None, 'log_penambahan_kerja', 'users', ['diproses_hr'], ['id_user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log_penambahan_kerja', type_='foreignkey')
    op.alter_column('log_penambahan_kerja', 'status',
               existing_type=sa.Enum('menunggu_pm', 'disetujui_pm', 'ditolak_pm', 'menunggu_hr', 'disetujui_hr', 'ditolak_hr', 'menunggu_direktur'),
               type_=mysql.ENUM('menunggu_pm', 'disetujui_pm', 'ditolak_pm', 'menunggu_hr', 'disetujui_hr', 'ditolak_hr'),
               existing_nullable=False)
    op.drop_column('log_penambahan_kerja', 'keterangan_disetujui_hr')
    op.drop_column('log_penambahan_kerja', 'diproses_hr')
    # ### end Alembic commands ###
